trigger:
- main
name: $(date:yyyyMMdd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
resources:
  repositories:
    - repository: corePipelines
      type: git
      name: Core/Pipelines
steps:
  - template: templates/Orca_IAC_scan_template.yml@corePipelines
    parameters:
      ORCA_SECURITY_API_TOKEN: '$(ORCA_SECURITY_API_TOKEN)'
