variable "environment" {
  type        = string
  description = "Mandatory. Deployment environment: dev, test, uat, prod, sandbox, np1, np2, or np3. POC deployments use sandbox. The existing-LZ aliases np1, np2, and np3 represent dev, test, and uat respectively."
  default     = null

  validation {
    condition     = var.environment == null ? true : contains(["dev", "test", "uat", "prod", "sandbox", "np1", "np2", "np3"], lower(trimspace(var.environment)))
    error_message = "environment must be one of: dev, test, uat, prod, sandbox, np1, np2, np3. POC deployments must use sandbox."
  }
}

variable "application" {
  type        = string
  description = "Mandatory. Application / service this resource belongs to. Non-empty normalized application or platform identifier."
  default     = null

  validation {
    condition     = var.application == null ? true : length(trimspace(var.application)) > 0
    error_message = "application must be non-empty when supplied."
  }
}

variable "owner" {
  type        = string
  description = "Mandatory. Accountable owner: a non-empty team name, or a distribution-list email address."
  default     = null

  validation {
    condition = var.owner == null ? true : (
      length(trimspace(var.owner)) > 0 &&
      (!strcontains(var.owner, "@") || can(regex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", var.owner)))
    )
    error_message = "owner must be a non-empty team name, or - if it contains \"@\" - a well-formed distribution-list email address."
  }
}

variable "source_repo" {
  type        = string
  description = "Mandatory. Repository or IaC path that provisions the resource, as a URI (e.g. ado://Compeer/landing-zone, https://github.com/org/repo)."
  default     = null

  validation {
    condition     = var.source_repo == null ? true : can(regex("^[a-zA-Z][a-zA-Z0-9+.-]*://\\S+$", trimspace(var.source_repo)))
    error_message = "source_repo must be a non-empty URI with a scheme, e.g. ado://Compeer/landing-zone or https://github.com/org/repo."
  }
}

variable "created_on" {
  type        = string
  description = "Mandatory. First deployment date in YYYY-MM-DD format. Supply a persisted value such as one generated by time_static; do not use timestamp()."
  default     = null

  validation {
    condition     = var.created_on == null ? true : can(timecmp("${var.created_on}T00:00:00Z", "${var.created_on}T00:00:00Z"))
    error_message = "created_on must be a real calendar date in YYYY-MM-DD format (e.g. 2026-09-02, not 2026-99-99 or 2026-02-30)."
  }
}

variable "criticality_tier" {
  type        = string
  description = "Mandatory. Business and operational criticality: tier-0, tier-1, tier-2, tier-3, or tier-4."
  default     = null

  validation {
    condition     = var.criticality_tier == null ? true : contains(["tier-0", "tier-1", "tier-2", "tier-3", "tier-4"], var.criticality_tier)
    error_message = "criticality_tier must be one of: tier-0, tier-1, tier-2, tier-3, tier-4."
  }
}

variable "data_classification" {
  type        = string
  description = "Mandatory. Data classification: public | internal | confidential | restricted."
  default     = null

  validation {
    condition     = var.data_classification == null ? true : contains(["public", "internal", "confidential", "restricted"], var.data_classification)
    error_message = "data_classification must be public, internal, confidential, or restricted."
  }
}

variable "lifecycle_state" {
  type        = string
  description = "Mandatory. Resource lifecycle status: active, temporary, pilot, decommission-pending, retired, or exempt."
  default     = null

  validation {
    condition     = var.lifecycle_state == null ? true : contains(["active", "temporary", "pilot", "decommission-pending", "retired", "exempt"], var.lifecycle_state)
    error_message = "lifecycle_state must be one of: active, temporary, pilot, decommission-pending, retired, exempt."
  }
}

variable "cost_center" {
  type        = string
  description = "Mandatory. Cost center / chargeback key. Non-empty when supplied - a stricter Finance-approved format is deliberately not enforced yet; confirm the exact format with Finance before adding one."
  default     = null

  validation {
    condition     = var.cost_center == null ? true : length(trimspace(var.cost_center)) > 0
    error_message = "cost_center must be non-empty when supplied."
  }
}

variable "gl_category" {
  type        = string
  description = "Mandatory. General-ledger category for financial reporting. Non-empty when supplied - a stricter Finance-approved format is deliberately not enforced yet; confirm the exact format with Finance before adding one."
  default     = null

  validation {
    condition     = var.gl_category == null ? true : length(trimspace(var.gl_category)) > 0
    error_message = "gl_category must be non-empty when supplied."
  }
}

variable "appcode" {
  type        = string
  description = "Mandatory. Application code - the same short identifier the naming module's own `appcode` input uses, so a resource's tag matches its actual name prefix rather than drifting from it. At most 9 letters."
  default     = null

  validation {
    condition     = var.appcode == null ? true : can(regex("^[a-zA-Z]{1,9}$", trimspace(var.appcode)))
    error_message = "appcode must be 1-9 letters only (no digits, hyphens, or underscores) - the same constraint the naming module enforces on its own appcode input, since this tag exists to mirror it."
  }
}

variable "application_component" {
  type        = string
  description = "Optional. Sub-component of the application. Non-empty when supplied."
  default     = null

  validation {
    condition     = var.application_component == null ? true : length(trimspace(var.application_component)) > 0
    error_message = "application_component must be non-empty when supplied."
  }
}

variable "modified_on" {
  type        = string
  description = "Optional. Last-modified date (ISO-8601). Must not be before created_on when both are set (see checks.tf)."
  default     = null

  validation {
    condition     = var.modified_on == null ? true : can(timecmp("${var.modified_on}T00:00:00Z", "${var.modified_on}T00:00:00Z"))
    error_message = "modified_on must be a real calendar date in YYYY-MM-DD format."
  }
}

variable "created_by" {
  type        = string
  description = "Deployment mechanism. Fixed to Terraform; explicit null values resolve to this default."
  default     = "Terraform"
  nullable    = false

  validation {
    condition     = var.created_by == "Terraform"
    error_message = "created_by must be Terraform."
  }
}

variable "dr_tier" {
  type        = string
  description = "Conditional. Disaster-recovery tier: gold (multi-zone/multi-region, tested failover, strict RTO/RPO), silver (zone-redundant or region-recoverable, scheduled backups), bronze (backup/restore-based recovery, relaxed RTO/RPO), or none (no formal DR requirement - rebuild from IaC or discard)."
  default     = null

  validation {
    condition     = var.dr_tier == null ? true : contains(["gold", "silver", "bronze", "none"], var.dr_tier)
    error_message = "dr_tier must be one of: gold, silver, bronze, none."
  }
}

variable "time_bound_exception" {
  type        = bool
  description = "Whether this sandbox resource has an approved, time-bound exception. May be true only when environment is sandbox and lifecycle_state is exempt."
  default     = false
}

variable "expiration_date" {
  type        = string
  description = "Required when environment is sandbox and not permitted for any other environment. Must be a real YYYY-MM-DD date and must not be before created_on when both are set."
  default     = null

  validation {
    condition     = var.expiration_date == null ? true : can(timecmp("${var.expiration_date}T00:00:00Z", "${var.expiration_date}T00:00:00Z"))
    error_message = "expiration_date must be a real calendar date in YYYY-MM-DD format."
  }
}

variable "additional_tags" {
  type        = map(string)
  description = "Additional organization-specific tags. Standard tag keys are rejected and must use their dedicated inputs."
  default     = {}
}
