hub_subscription_id   = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
spoke_subscription_id = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
hub_rg_name           = "rg-test-2"
spoke_rg_name         = "rgr-test"
hub_vnet_name         = "vnet-test-2"
spoke_vnet_name       = "vnet-test"
