---
- name: Gather Linux service facts
  ansible.builtin.service_facts:

- name: Validate expected Linux services
  ansible.builtin.assert:
    that:
      - "item + '.service' in ansible_facts.services"
      - "ansible_facts.services[item + '.service'].state == 'running'"
    fail_msg: "{{ item }} is not running"
  loop: "{{ validation_expected_linux_services_base + [validation_linux_chrony_service_name] }}"
  loop_control:
    label: "{{ item }}"

- name: Validate SSH port
  ansible.builtin.wait_for:
    port: 22
    timeout: 10
