variable "application_name" { type = string }
variable "environment" { type = string }
variable "location" { type = string }
variable "tenant_id" { type = string }
variable "tags" {
  type    = map(string)
  default = {}
}
variable "resource_group" { type = any }
variable "log_analytics" { type = any }
variable "action_group" { type = any }
variable "virtual_network" { type = any }
variable "route_table" { type = any }
variable "network_security_group" { type = any }
variable "private_dns_zones" { type = any }
variable "private_dns_links" { type = any }
variable "private_dns_records" { type = any }
variable "nat_gateway" { type = any }
variable "nat_public_ip" { type = any }
variable "load_balancer_public_ip" { type = any }
variable "storage_account" { type = any }
variable "key_vault" { type = any }
variable "key_vault_secrets" { type = any }
variable "key_vault_access_policies" { type = any }
variable "network_interface" { type = any }
variable "application_security_group" { type = any }
variable "availability_set" { type = any }
variable "windows_vm" { type = any }
variable "windows_vm_data_disks" { type = any }
variable "windows_vm_domain_join" { type = any }
variable "windows_vm_extensions" { type = any }
variable "load_balancer" { type = any }
variable "sql_server" { type = any }
variable "sql_databases" { type = any }
variable "sql_auditing_policy" { type = any }
variable "sql_security_alert_policy" { type = any }
variable "sql_private_endpoint" { type = any }
variable "key_vault_diagnostics" { type = any }
variable "sql_diagnostics" { type = any }
