---
- name: Resolve Azure Monitor Agent package path for Linux
  ansible.builtin.set_fact:
    ama_linux_package_path: "{{ ama_installer_download_dir_linux }}/azuremonitoragent.{{ 'rpm' if ansible_os_family == 'RedHat' else 'deb' }}"

- name: Download Azure Monitor Agent package
  ansible.builtin.get_url:
    url: "{{ ama_linux_package_url }}"
    dest: "{{ ama_linux_package_path }}"
    mode: '0644'

- name: Install Azure Monitor Agent on RedHat family
  ansible.builtin.yum:
    name: "{{ ama_linux_package_path }}"
    state: present
    disable_gpg_check: true
  when: ansible_os_family == 'RedHat'
  notify: restart ama linux

- name: Install Azure Monitor Agent on Debian family
  ansible.builtin.apt:
    deb: "{{ ama_linux_package_path }}"
    state: present
  when: ansible_os_family == 'Debian'
  notify: restart ama linux
