---
baseline_packages_linux_common:
  - curl
  - jq
  - unzip
  - rsyslog
  - chrony
  - openssl
  - ca-certificates
  - python3-pip
baseline_packages_linux_family:
  RedHat:
    - audit
    - bind-utils
    - nmap-ncat
  Debian:
    - auditd
    - dnsutils
    - netcat-openbsd
baseline_packages_linux: "{{ baseline_packages_linux_common + baseline_packages_linux_family.get(ansible_os_family, []) }}"
baseline_services_linux:
  - rsyslog
linux_disable_root_ssh: true
linux_password_authentication: false
linux_umask: "027"
linux_auditd_enabled: true
linux_fips_mode_required: false
linux_open_ports_allowlist:
  - 22
  - 443
